// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Renal37/go-musthave-diploma-tpl/internal/models (interfaces: AccrualService)

// Package mock_models is a generated GoMock package.
package mock_models

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAccrualService is a mock of AccrualService interface.
type MockAccrualService struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualServiceMockRecorder
}

// MockAccrualServiceMockRecorder is the mock recorder for MockAccrualService.
type MockAccrualServiceMockRecorder struct {
	mock *MockAccrualService
}

// NewMockAccrualService creates a new mock instance.
func NewMockAccrualService(ctrl *gomock.Controller) *MockAccrualService {
	mock := &MockAccrualService{ctrl: ctrl}
	mock.recorder = &MockAccrualServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualService) EXPECT() *MockAccrualServiceMockRecorder {
	return m.recorder
}

// CalculateAccrual mocks base method.
func (m *MockAccrualService) CalculateAccrual(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CalculateAccrual", arg0)
}

// CalculateAccrual indicates an expected call of CalculateAccrual.
func (mr *MockAccrualServiceMockRecorder) CalculateAccrual(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateAccrual", reflect.TypeOf((*MockAccrualService)(nil).CalculateAccrual), arg0)
}

// StartCalculationAccruals mocks base method.
func (m *MockAccrualService) StartCalculationAccruals(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartCalculationAccruals", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartCalculationAccruals indicates an expected call of StartCalculationAccruals.
func (mr *MockAccrualServiceMockRecorder) StartCalculationAccruals(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCalculationAccruals", reflect.TypeOf((*MockAccrualService)(nil).StartCalculationAccruals), arg0)
}
